# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Squirrel' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Squirrel
  pod 'JFContactsPicker', '~> 1.0'

  target 'SquirrelTests' do
    inherit! :search_paths
    
  end

  target 'SquirrelUITests' do
    inherit! :search_paths
  end

end
